export const TABLE_HEAD = [
  "",
  "Lite",
  "Basic",
  "Pro",
  "Ultra",
  "Premium",
  "Enterprise",
];
export const TABLE_BOTTOM = [
  {
    Url: "#",
    Label: "Get Started",
  },
  {
    Url: "#",
    Label: "Get Started",
  },
  {
    Url: "#",
    Label: "Get Started",
  },
  {
    Url: "#",
    Label: "Get Started",
  },
  {
    Url: "#",
    Label: "Get Started",
  },
  {
    Url: "#",
    Label: "Contact us",
  },
];

export const CHECK_ICON = ["Y", "N"];

export const PRICE_LIST_AMOUNT = [
  {
    Column1: "Monthly Price ($)",
    Free: "0",
    Lite: "19",
    Basic: "49",
    Pro: "99",
    Ultra: "199",
    Premium: "499",
    Enterprise: "Custom",
  },
];
export const TOP_PRODUCT_PRICE_LIST = [
  {
    Column1: "Monthly Transactions",
    Free: 50,
    Lite: 200,
    Basic: 800,
    Pro: 1500,
    Ultra: 3000,
    Premium: 10000,
    Enterprise: "Custom",
  },
  {
    Column1: "Additional Orders",
    Free: "$0.2",
    Lite: "$0.2",
    Basic: "$0.15",
    Pro: "$0.15",
    Ultra: "$0.1",
    Premium: "$0.05",
    Enterprise: "Custom",
  },
  {
    Column1: "Number of Campaigns",
    Free: 1,
    Lite: 3,
    Basic: 5,
    Pro: 15,
    Ultra: 40,
    Premium: 100,
    Enterprise: "Custom",
  },
  {
    Column1: "Number of Integrations",
    Free: 1,
    Lite: 2,
    Basic: 3,
    Pro: 4,
    Ultra: "Unlimited",
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: " Giftcard Program",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Store Credits",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Loyalty Program",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Coupons",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Referral Program",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Automation Workflows",
    Free: "N",
    Lite: 1,
    Basic: 3,
    Pro: 6,
    Ultra: 10,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
];
export const REMAINING_PRODUCT_PRICE_LIST = [
  {
    Column1: "Import Giftcards",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Widget Customization",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Resend Emails",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Custom Gift Card Artworks",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },

  {
    Column1: "Expiring Store Credits",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Check Balance Page",
    Free: "Y",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Workflow Delay Action",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Print at Home",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },

  {
    Column1: "Giftcard Discounts & Promotions",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Schedule Gift Card Delivery",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Default Email Customization",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Reports",
    Free: "N",
    Lite: "Y",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Custom Email Templates",
    Free: "N",
    Lite: "N",
    Basic: 3,
    Pro: 10,
    Ultra: 20,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },
  {
    Column1: "Barcode Generation",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Apple Wallet Integration",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Bulk Giftcard Creation",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Web POS",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Physical Gift Card Support",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Multi Currency Support",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Supported POS Integrations",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Remove Branding",
    Free: "N",
    Lite: "N",
    Basic: "Y",
    Pro: "Y",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Team Management",
    Free: "N",
    Lite: "N",
    Basic: 5,
    Pro: 10,
    Ultra: 25,
    Premium: "Unlimited",
    Enterprise: "Unlimited",
  },

  {
    Column1: "VIP Tiers",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "Y",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "B2B Distribution",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "Multi-Store Gift Cards",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "N",
    Enterprise: "Custom\n($10 per additional store)",
  },
  {
    Column1: "Two Factor Authentication",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "Y",
    Enterprise: "Y",
  },
  {
    Column1: "API Access",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "N",
    Enterprise: "Y",
  },
  {
    Column1: "Custom 3rd Party POS Support",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "N",
    Enterprise: "Y",
  },
  {
    Column1: "Account Manager",
    Free: "N",
    Lite: "N",
    Basic: "N",
    Pro: "N",
    Ultra: "N",
    Premium: "N",
    Enterprise: "Y",
  },
  // {
  //   Column1: "Infrastructure",
  //   Free: "Shared",
  //   Lite: "Shared",
  //   Basic: "Shared",
  //   Pro: "Shared",
  //   Ultra: "Shared",
  //   Premium: "Shared",
  //   Enterprise: "Shared or Dedicated",
  // },
];
